import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import * as Sentry from "@sentry/react";
import { createStore, compose } from "redux";

const sentryReduxEnhancer = Sentry.createReduxEnhancer({
  // Optionally pass options listed below
});


Sentry.init({
  dsn: "https://9f4c12a83f11496798c06ec147a90999@o60189.ingest.sentry.io/6368333",
  maxBreadcrumbs: 50,
  debug: true,
});

const Home: NextPage = () => {
  const sampleReducer = (state: any, action: any) => {
    if (typeof state === 'undefined') {
      return 0
    }

    switch (action.type) {
      case 'BING':
        return "BONG"
      case 'PING':
        return "PONG"
      case 'ERROR_FROM_APP':
        return "OOPSIE"
      default:
        return state
    }
  }
  const store = createStore(sampleReducer, sentryReduxEnhancer);

  const dispatch = (reducerType: string) => {
    store.dispatch({ type: `${reducerType}` });      
    try {
      if (reducerType == 'ERROR_FROM_APP') throw(new Error('I just broke the wolrd.'))
    } catch (error) {
      Sentry.captureException(error, store.getState());
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <button onClick={() => { dispatch('ERROR_FROM_APP')}}>Break the world</button>
        <button onClick={() => { dispatch('BING')}}>BING</button>
        <button onClick={() => { dispatch('PING')}}>PING</button>
        

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
